### ISSUE TITLE
Satisplanory does not show from which Satisfactory installation/branch data was read and does not allow to switch in UI

### ISSUE THREAD

**Issue by meolus** [elcheapogary/satisplanory#5]
In Epic Games Launcher you can have the Early Access and the Experimental version both installed in parallel at the same time.

Currently Satisplanory finds some installation automatically, but you don't see which version/branch was selected and are not able to switch between. (Of course you can look it up (+ change) in Satisplanory.json, but that's not very user friendly.)

Expected:
1.) You see which Satisfactory installation's / version's data is used.
2.) You can switch between Satisfactory  installation's / version's being used.
3.) Last selection is saved and restored after restart of Satisplanory.

Ideas/Hints:
1.) This may be a drop down in main menu like on https://satisfactory-calculator.com or https://satisfactorytools.com, so expected 1.) & 2.) are combined.
2.) Since you are already considering that attempts to find Satisfactory directory automatically will fail, you may need to be able to add/remove Satisfactory directories manually to the list of available installations/versions, too?!

**Comment by elcheapogary** [comment]
Thanks, your suggestion makes sense.

Maybe when initially finding Satisfactory installations, if multiple are found (user may even have 3 installations if they have both Steam and Epic), we can present them with a menu of which installation's data they would like to use.

We could then record all Satisfactory installations found for later use but use the selected installation.

We could then add a File -> Change Satisfactory Installation menu option, which would rescan for Epic/Steam installation and recheck validity of previously manually added installations, and present menu to choose a valid installation, including any previously manually added installations that are still valid.

What do you think?

**Comment by meolus** [comment]
Sounds good.

**Comment by meolus** [comment]
Was added in v1.6.0 below "File" -> "Select Satisfactory Installation". You can add new installation, select other installation and view selected installation. Thank you, great work!
